title: REDCap (Research Data Capture) at Griffith
description: Documentation and self-directed learning for the REDCap instance at Griffith University.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/gu_logo.png"

# Aux links for the upper right navigation
aux_links:
  "GU Library Website":
    - "https://www.griffith.edu.au/library"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# To disable support for mermaid diagrams (https://mermaid.js.org),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.1.0"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code

# Define callout colours and titles
callouts:
  warning:
    title: Remember
    color: red
  info:
    title: Info
    color: blue
  success:
    title: Success
    color: green
  highlight:
    title: Important
    color: yellow
  note:
    title: Note
    color: purple
